version: '3'
services:
  user:
    tty: true
    build: ./docker/api
    working_dir: /go/src/github.com/SeijiOmi/user
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/SeijiOmi/user
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: sample
      DB_ADDRESS: user-db:3306
      POST_URL: http://post:8090
      POINT_URL: http://point:9000
    networks:
      - my_network
  user-db:
    build: ./docker/db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - my_network

  user-mock-point:
    build: ./docker/json-server/point
    ports:
      - '3040:3000'
    volumes:
      - ./docker/json-server/point/:/data/
    command: json-server -w db.json --routes route.json -m middleware.js --host 0.0.0.0
    networks:
      - my_network

  user-mock-post:
    build: ./docker/json-server/post
    ports:
      - '3050:3000'
    volumes:
      - ./docker/json-server/post/:/data/
    command: json-server -w db.json --routes route.json -m middleware.js --host 0.0.0.0
    networks:
      - my_network

networks:
  my_network:
    external: true
