version: '3'
services:
  api:
    tty: true
    links:
      - mysql
    image: zemisemi/gin-template
    working_dir: /go/src/github.com/SeijiOmi/gin-tamplate
    entrypoint:
      - dockerize
      - -timeout
      - 60s
      - -wait
      - tcp://mysql:3306
    # command: gin -i --all run main.go
    # build:
    #   context: .
    #   dockerfile: ./docker/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/SeijiOmi/gin-tamplate
  mysql:
    build: ./docker/db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/var/log/mysql
