apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: ap
    back: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap
      back: user
  template:
    metadata:
      labels:
        app: ap
        back: user
    spec:
      containers:
      - name: user
        image: zemisemi/user
        ports:
        - containerPort: 8080
        command:
          - sh
          - -c
          - go run main.go
        env:
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "password"
          - name: DB_NAME
            value: "sample"
          - name: DB_ADDRESS
            value: "user-db:3306"
          - name: POST_URL
            value: "http://post"
          - name: POINT_URL
            value: "http://point"
