version: 2
jobs:
  build:
    machine: true
    steps:
      # これでリポジトリのデータがカレントに持ってこられるのかな恐らく。
      - checkout

      - run:
          name: create docker network
          command: docker network create my_network

      - run:
          name: dockerize をインストール
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: docker-compose up
          command: docker-compose up -d

      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run:
          name: stop
          command: docker-compose stop
      - run:
          name: up
          command: docker-compose up -d

      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run:
          name: ping-test
          command: docker-compose exec user ping user-db -c 5

      - run:
          name: lint
          command: docker-compose exec user bash lint.sh

      - run:
          name: testing
          command: docker-compose exec user make
